# Generated by Django 5.1.1 on 2024-09-08 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('careers_link', models.URLField(default=None)),
                ('linkedin_link', models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('linkedin_link', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('contacted', models.CharField(choices=[('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('MESSAGED', 'Messaged'), ('REPLIED', 'Replied'), ('STRONG_CONNECTION', 'Established Connection')], max_length=255)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobLanderAPI.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=255)),
                ('submitted_cv', models.FileField(upload_to='')),
                ('ats_score', models.SmallIntegerField(default=0)),
                ('stage', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSESSMENT', 'Assessment'), ('INTERVIEW', 'Interview'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], max_length=255)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobLanderAPI.company')),
                ('contacted_employees', models.ManyToManyField(to='JobLanderAPI.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JobLanderAPI.application')),
            ],
        ),
    ]
