# Generated by Django 5.1.1 on 2024-09-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobLanderAPI', '0003_alter_application_user_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='careers_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='linkedin_link',
            field=models.URLField(null=True),
        ),
    ]
