# Generated by Django 5.1.1 on 2024-09-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobLanderAPI', '0005_alter_application_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Company',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='application',
            name='submitted_cv',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
