# Generated by Django 5.1.1 on 2024-09-26 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobLanderAPI', '0006_rename_company_application_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 26, 19, 2, 37, 70300)),
        ),
    ]
