# Generated by Django 5.1.1 on 2024-09-26 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobLanderAPI', '0007_alter_application_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='submission_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
