# Generated by Django 5.1.1 on 2024-09-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobLanderAPI', '0008_alter_application_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='contacted_employees',
            field=models.ManyToManyField(blank=True, to='JobLanderAPI.employee'),
        ),
    ]
