# Generated by Django 5.1.1 on 2024-09-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobLanderAPI', '0010_alter_application_link_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contacted',
            field=models.CharField(choices=[('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('MESSAGED', 'Messaged'), ('REPLIED', 'Replied'), ('STRONG_CONNECTION', 'Strong Connection')], max_length=255),
        ),
    ]
